sudo: true
language: generic
git:
  submodules:
    false

matrix:
  include:
    -
      env:
        - ID=api/lint
        - PROJECT_DIR=$TRAVIS_BUILD_DIR/apps/api
        - INSTALL='yarn install'
        - ACTION='yarn lint'
      language: node_js
      node_js:
        - "10"
    -
      env:
        - ID=api/unit-tests
        - PROJECT_DIR=$TRAVIS_BUILD_DIR/apps/api
        - INSTALL='yarn install'
        - ACTION='yarn test:unit'
      language: node_js
      node_js:
        - "10"
    -
      env:
        - ID=api/e2e-tests
        - PROJECT_DIR=$TRAVIS_BUILD_DIR/apps/api
        - INSTALL='yarn install'
        - ACTION='yarn test:e2e'
      language: node_js
      node_js:
        - "10"
    -
      env:
        - ID=explorer/unit-tests
        - PROJECT_DIR=$TRAVIS_BUILD_DIR/apps/ethvm
        - INSTALL='yarn install'
        - ACTION='yarn test:unit'
      language: node_js
      node_js:
        - "10"
    -
      env:
        - ID=processing/lint
        - PROJECT_DIR=$TRAVIS_BUILD_DIR/apps/processing
        - INSTALL=''
        - ACTION='./gradlew --no-daemon :ktlintCheck'
      language: generic
    -
      env:
        - ID=processing/kafka-streams/unit-tests
        - PROJECT_DIR=$TRAVIS_BUILD_DIR/apps/processing
        - INSTALL=''
        - ACTION='./gradlew --no-daemon :kafka-streams:test'
      language: generic

before_install:
  - ./.travis/before-install.sh

install:
  - cd $PROJECT_DIR
  - eval $INSTALL

script:
  - cd $PROJECT_DIR
  - eval $ACTION

deploy:
  provider: script
  script: bash $TRAVIS_BUILD_DIR/.travis/docker-push.sh
  on:
    branch: master
