sudo: false
language: generic
addons:
  rethinkdb: "2.3.4"
services:
  - redis-server
  - mongodb
env:
  - ETHVM_RETHINK_DB_HOST=localhost
  - ETHVM_RETHINK_DB_PORT=28015

matrix:
  include:
    -
      env: PROJECT=apps/ethvm
      language: node_js
      node_js:
        - "10"
    -
      env: PROJECT=apps/ethvm-e2etest
      language: node_js
      node_js:
        - "10"
    -
      env: PROJECT=apps/serverunittest
      language: node_js
      node_js:
        - "10"
    -
      env: PROJECT=apps/server
      language: node_js
      node_js:
        - "10"

before_install:
  - 'if [ $PROJECT = "apps/ethvm" ]; then cd $TRAVIS_BUILD_DIR/apps/ethvm; fi'
  - 'if [ $PROJECT = "apps/server" ]; then cd $TRAVIS_BUILD_DIR/apps/server; fi'
  - 'if [ $PROJECT = "apps/ethvm-e2etest" ]; then yarn install; yarn testprovider generate; cd $TRAVIS_BUILD_DIR/apps/server; ls; pwd; fi'
  - 'if [ $PROJECT = "apps/serverunittest" ]; then cd $TRAVIS_BUILD_DIR/apps/server; fi'

install:
  - yarn install

before_script:
  - 'if [ $PROJECT = "apps/ethvm" ]; then cd $TRAVIS_BUILD_DIR/apps/ethvm; fi'
  - 'if [ $PROJECT = "apps/server" ]; then cd $TRAVIS_BUILD_DIR/apps/server; fi'
  - 'if [ $PROJECT = "apps/ethvm-e2etest" ]; then cd $TRAVIS_BUILD_DIR/apps/server; fi'
  - 'if [ $PROJECT = "apps/serverunittest" ]; then cd $TRAVIS_BUILD_DIR/apps/server; fi'

script:
  - 'if [ $PROJECT = "apps/server" ]; then yarn lint;  fi'
  - 'if [ $PROJECT = "apps/ethvm-e2etest" ]; then yarn test:e2e;  fi'
  - 'if [ $PROJECT = "apps/serverunittest" ]; then yarn test:unit;  fi'
