version: '3.6'

networks:
  web:
    external: true

services:

  traefik:
    image: traefik:1.6.2-alpine
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/config/traefik/traefik.toml:/etc/traefik/traefik.toml
    networks:
      - web
    ports:
      - "80:80"
      - "81:81"

  ethvm:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    volumes:
      - ".:/var/ethvm"
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.default.protocol=http"
      - "traefik.frontend.rule=Host:ethvm.lan"
      - "traefik.port=80"
      - "traefik.frontend.headers.customResponseHeaders=Access-Control-Allow-Origin:*||Access-Control-Allow-Credentials:true"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.backend=ethvm"
    environment:
      - ETHVM_HOST=0.0.0.0
      - ETHVM_PORT=80
      - ETVHM_DOCKER=true

  ethvm_socket_server:
    image: enkryptio/ethvm-socket-server:latest
    restart: unless-stopped
    depends_on:
      - geth
      - redis
      - rethinkdb
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.default.protocol=http"
      - "traefik.frontend.rule=Host:ws.ethvm.lan"
      - "traefik.port=3000"
      - "traefik.frontend.headers.customResponseHeaders=Access-Control-Allow-Origin:http://ethvm.lan||Access-Control-Allow-Credentials:true"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.backend=ethvm_socket_server"

  redis:
    image: redis:4.0.9-alpine
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.default.protocol=http"
      - "traefik.frontend.rule=Host:redis.ethvm.lan"
      - "traefik.port=6379"
      - "traefik.backend=redis"

  rethinkdb:
    image: enkryptio/rethinkdb:latest
    restart: unless-stopped
    networks:
      - web
    ports:
      - "28015:28015"
      - "8080:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.default.protocol=http"
      - "traefik.frontend.rule=Host:rethink.ethvm.lan"
      - "traefik.port=28015"
      - "traefik.backend=rethinkdb"
      - "traefik.dashboard.frontend.rule=Host:rethink.dashboard.ethvm.lan"
      - "traefik.dashboard.protocol=http"
      - "traefik.dashboard.backend=ethvm_socket_server"
      - "traefik.dashboard.port=8080"

  geth:
    image: enkryptio/go-ethereum:latest
    restart: unless-stopped
    depends_on:
      - rethinkdb
    volumes:
      - ./docker/volumes/geth/:/geth
      - ./docker/config/geth/genesis.json:/genesis.json
    networks:
      - web
    ports:
      - "9545:9545"
    labels:
      - "traefik.enable=true"
      - "traefik.default.protocol=http"
      - "traefik.frontend.rule=Host:geth.ethvm.lan"
      - "traefik.port=9545"
      - "traefik.backend=geth"
    environment:
      - RETHINKDB_USE_URL_FORMAT=true
      - RETHINKDB_URL=http://admin:1234@rethinkdb:28015
    command:
      - /bin/sh
      - -c
      - |
        geth --networkid="1114" --datadir="/geth/" --ethvm --ethvm.remote init /genesis.json
        geth --networkid="1114" --datadir="/geth/" --syncmode full --mine --etherbase '0xaD4A113E28C7857dB9f24336e4ED83F6dd883DF7' --ethvm --ethvm.remote --rpc --rpcaddr "0.0.0.0" --rpcport 9545 --gcmode archive
