version: '2.4'

volumes:
  mongodb-volume:

services:

  mongodb:
    image: enkryptio/mongodb-dev:${MONGODB_VERSION}
    restart: unless-stopped
    volumes:
      - mongodb-volume:/data/db
      - ./datasets:/datasets
    ports:
      - 27017:27017
    command:
      - /bin/sh
      - -c
      - |
          set -x
          mongod --bind_ip 0.0.0.0 --quiet --slowms 10000 &
          sleep 5
          mongorestore --archive="/datasets/mainnet_sample.mongo.archive"
          kill -9 $$(pgrep mongod)
          sleep 5
          mongod --bind_ip 0.0.0.0 --quiet --slowms 10000
