---
- name: "Generate kafka_server fact"
  set_fact: kafka_server="{{ kafka_server_defaults | combine(kafka_server) }}"

- name: "Generate kafka_healtcheck_address fact"
  set_fact: kafka_healthcheck_address="{{ ((kafka_server.host_name | default('127.0.0.1')) == '') | ternary('127.0.0.1', kafka_server.host_name) }}"
  when: kafka_healthcheck_address == ""

- name: "Generate kafka_producer fact"
  set_fact: kafka_producer="{{ kafka_producer_defaults | combine(kafka_producer) }}"

- name: "Generate generic unique machine id integer"
  # NB: This uses a combination of root partition UUID + network interface MAC address.
  shell: ( test -r /etc/fstab && find /dev/disk/by-uuid/ -type l -printf "%f\n" | sort | head -1 | grep --ignore-case --only-matching --extended-regexp --max 1 '[0-9a-f]{3,}[0-9a-f-]+' | tr -d '-' || echo '0' ; ifconfig | grep --ignore-case --only-matching --extended-regexp '([0-9a-f]{2}:){5}[0-9a-f]{2}' | tr -d ':' | tr -d '\n') | python -c 'import sys; x, y = sys.stdin.read().split(chr(10))[0:2]; x = int(x, 16); y = int(y, 16); sys.stdout.write((str(x + y)[-9:])); sys.exit(1 if x == 0 and y == 0 else 0)'
  register: machineidinteger
  changed_when: False
  check_mode: False
  when: kafka_generate_broker_id | bool

- name: "Use generated unique machine id integer as broker id"
  set_fact: kafka_broker_id={{ machineidinteger.stdout_lines[0] }}
  when: kafka_generate_broker_id | bool

- name: "Raise reserved broker id range"
  set_fact: kafka_reserved_broker_max_id=1000000000
  when: kafka_generate_broker_id | bool and kafka_version | version_compare('0.9.0.0', '>=')

- name: "Generate the zookeeper hosts connection string"
  set_fact: kafka_zookeeper_connection_string="{{ kafka_zookeeper_hosts | join(':' ~ kafka_zookeeper_port ~ ',') }}:{{ kafka_zookeeper_port }}"

- name: "Generate the kafka hosts connection string"
  set_fact: kafka_connection_string="{{ kafka_hosts | join(':' ~ kafka_server.port ~ ',') }}:{{ kafka_server.port }}"

- name: "Render and write out kafka configuration files"
  template: src=usr/local/kafka/config/{{ item }}.j2 dest="{{ kafka_conf_dir }}/{{ item }}" mode=0640 owner={{ kafka_user }} group={{ kafka_group }}
  sudo: yes
  with_items:
    - server.properties
    - producer.properties
    - consumer.properties
    - log4j.properties
  notify:
    - restart kafka

- name: "Render and write out kafka user env file"
  template: src=etc/defaults/kafka.j2 dest="/etc/default/kafka" mode=0644 owner=root group=root
  sudo: yes
  notify:
    - restart kafka

- name: "Enable kafka system service"
  service: name=kafka state=started enabled=yes
  sudo: yes
  tags:
    - kafka-install

- name: "Link alternate logs directory and touch output files"
  shell: "( test ! -e /usr/local/kafka/logs || rm -rf /usr/local/kafka/logs ) && ln -s {{ kafka_log_dir }} /usr/local/kafka/logs && touch {{ kafka_log_dir }}/state-change.log {{ kafka_log_dir }}/kafkaServer.out && chown {{ kafka_user }}:{{ kafka_group }} {{ kafka_log_dir }}/state-change.log {{ kafka_log_dir }}/kafkaServer.out"
  changed_when: False
  sudo: yes

- meta: flush_handlers

- name: "Wait for kafka to come up and open it's server port"
  wait_for: port={{ kafka_server.port }} host={{ kafka_healthcheck_address }} connect_timeout={{ kafka_port_test_timeout_seconds }} timeout={{ kafka_port_test_timeout_seconds }}
  ignore_errors: yes
  register: healthcheck
  tags:
    - kafka-healthcheck

- name: "Check kafka port test result"
  fail: msg="Kafka port not open on host={{ kafka_healthcheck_address }}, port={{ kafka_server.port }}"
  when: healthcheck.elapsed is defined and (healthcheck.elapsed >= kafka_port_test_timeout_seconds and kafka_port_test_timeout_seconds > 0)
  tags:
    - kafka-healthcheck
