---
- name: "Create kafka system group"
  group: name={{ kafka_group }} system=yes
  sudo: yes

- name: "Create kafka system user"
  user: name={{ kafka_user }} system=yes group={{ kafka_group }}
  sudo: yes

- name: "Add kafka utilities to /etc/profile* so they'll be available in $PATH"
  lineinfile: dest=/etc/profile.d/Z99-kafka.sh regexp="^export PATH=.*$" line='export PATH="${PATH}:/usr/local/kafka/bin"' state=present create=yes
  sudo: yes

