topics:

  - name: blocks
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact

  - name: uncles
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact

  - name: transactions
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact

  - name: receipts
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact

  - name: block-traces
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact

  - name: transaction-traces
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact

  - name: canonical-chain
    replicationFactor: 1
    partitions: 1
    config:
      cleanup.policy: compact

  - name: canonical-transactions
    replicationFactor: 1
    partitions: 1
    config:
      cleanup.policy: compact

  - name: canonical-transactions-concurrent
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact

  - name: transaction-ether-transfers
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact

  - name: canonical-transaction-ether-transfers
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact

  - name: contract-metadata
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact

  - name: contract-destructions
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact

  - name: contract-creations
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact


  - name: fungible-token-movements
    replicationFactor: 1
    partitions: 12
    config:
      retention.ms: -1

  - name: balances
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact

  - name: pending-transactions
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact

  - name: address-tx-events
    replicationFactor: 1
    partitions: 12
    config:
      retention.ms: -1

  - name: address-tx-counts
    replicationFactor: 1
    partitions: 12
    config:
      retention.ms: -1

  - name: miner-list
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact

  - name: contract-creator-list
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact

  - name: block-metrics-by-block
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact

  - name: block-metrics-by-day
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact

  - name: aggregate-block-metrics-by-day
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact

  - name: eth-tokens-list
    replicationFactor: 1
    partitions: 1
    config:
      cleanup.policy: compact

  - name: eth-tokens-list-by-symbol
    replicationFactor: 1
    partitions: 1
    config:
      cleanup.policy: compact

  - name: raw-exchange-rates
    replicationFactor: 1
    partitions: 1
    config:
      cleanup.policy: compact

  - name: token-exchange-rates
    replicationFactor: 1
    partitions: 1
    config:
      cleanup.policy: compact

  - name: processing-metadata
    replicationFactor: 1
    partitions: 1
    config:
      cleanup.policy: compact
